### ISSUE TITLE
oh my zsh not working

### ISSUE THREAD

**Issue by p1r473** [raisedadead/zsh-touchplus#1]
Hi, I keep getting this error
```
[oh-my-zsh] plugin 'zsh-touchplus' not found   
```

I followed the directions exactly and I am familiar with other Oh My Zsh plugins.
Are you sure the right title is `zsh-touchplus`?

**Comment by p1r473** [comment]
The directions are incorrect for OMZ

you need to check it out as touchplus and add it to plugin as touchplus

or have to rename plugin file to zsh-touchplus.plugin from touchplus.plugin

**Comment by raisedadead** [comment]
You are correct, it seems like an oversight – because I do not use OMZ. The instructions for OMZ should be:

```diff
plugins=(
  #...
-  zsh-touchplus
+  touchplus
  )
```

**Comment by raisedadead** [comment]
I have created https://github.com/raisedadead/zsh-touchplus/pull/3 - let me know if the new instructions work for you. Thanks.

**Comment by p1r473** [comment]
Yep that's good! @raisedadead

**Comment by raisedadead** [comment]
I have updated the instructions. Thanks again for bringing this up.
